apiVersion: v2
name: akka-monitor
description: A Helm chart for AkkaMonitor with Grafana and Prometheus Operator
type: application
version: 1.0.0
appVersion: "1.3"

dependencies:
  - name: grafana
    version: "8.6.2"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  
  - name: kube-prometheus-stack
    version: "65.3.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
