{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-log
  namespace: {{ include "akka-monitor.namespace" . }}
  labels:
    {{- include "akka-monitor.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
{{- end }}
