{{- if and .Values.akkaMonitor.enabled .Values.akkaMonitor.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "akka-monitor.fullname" . }}
  namespace: {{ include "akka-monitor.namespace" . }}
  labels:
    {{- include "akka-monitor.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "akka-monitor.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.akkaMonitor.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.akkaMonitor.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.akkaMonitor.networkPolicy.egress | nindent 4 }}
{{- end }}
