{{- if and .Values.akkaMonitor.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "akka-monitor.fullname" . }}
  namespace: {{ include "akka-monitor.namespace" . }}
  labels:
    {{- include "akka-monitor.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "akka-monitor.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: prometheus
    interval: {{ .Values.serviceMonitor.interval }}
    path: /metrics
{{- end }}
